### ISSUE TITLE
프로젝트 상세 페이지

### ISSUE THREAD

**Issue by soprue** [9weeks-app-web/team-3-sfacfolio#18]
### Todo

- [x] 상세 페이지 레이아웃 구현
- [x] 상세 페이지 데이터 받아와서 보여 주기
- [x] '댓글' 등록 구현
- [ ] '대댓글' 등록 구현
- [ ] '프로젝트 지원하기' 기능 구현

### 작업 기간

2024.01.03 ~ 2024.01.04 (예상)

---

### 참고 자료

react-calendar: https://velog.io/@khy226/리액트-앱에-달력react-calendar-적용하기
