### ISSUE TITLE
메인 페이지 - 섹션 헤더/카테고리 버튼/디자인 저격수

### ISSUE THREAD

**Issue by soprue** [9weeks-app-web/team-3-sfacfolio#2]
### Todo

- [x] 섹션 헤더 컴포넌트
- [x] 섹션 헤더 옆 더보기 버튼
- [x] 카테고리 버튼
- [x] 카테고리 캐러셀
- [x] 디자인 저격수 되기 컴포넌트

### 작업 기간

2023.12.29

### 참고
카테고리 캐러셀 레퍼런스: 노트폴리오
