### ISSUE TITLE
프로젝트 등록 페이지

### ISSUE THREAD

**Issue by kangkyeongseo** [9weeks-app-web/team-3-sfacfolio#20]
### Todo

- [ ] 사이드 프로젝트 등록 페이지 레이아웃 구현
- [ ] 사이드 프로젝트 등록 페이지 form 데이터 연결 
- [ ] 프리랜서/외주 등록 페이지 레이아웃 구현
- [ ] 프리랜서/외주 등록 페이지 form 데이터 연결 
  
### 작업 기간

2024.01.03 ~ 2024.01.04
