### ISSUE TITLE
로그인/회원가입/프로젝트 매칭 및 등록 완료 페이지

### ISSUE THREAD

**Issue by geonwooPark** [9weeks-app-web/team-3-sfacfolio#21]
### Todo

- [ ] 프로젝트 매칭
- [ ] 프로젝트 등록 완료 페이지
- [ ] 매칭 중 컴포넌트, 매칭 성공 컴포넌트
- [x] 로그인/회원가입(약관 모달, 본인인증, 정보입력, 아이디 찾기, 비밀번호 찾기 기능은 추후 optional로 구현)

### 작업 기간

2024.01.02 ~

---

### 어떤 버그 인가요?

> 버그에 대해 알려주세요

### 참고 자료(optional)

> 참고자료가 있다면 첨부해주세요.
