### ISSUE TITLE
프로젝트 목록 페이지 추가 및 헤더 컴포넌트 기능 추가

### ISSUE THREAD

**Issue by seonnn** [9weeks-app-web/team-3-sfacfolio#22]
### Todo

- [ ] 프로젝트 목록 페이지 레이아웃
  - [x] 프로젝트 매칭 메인 배너
  - [x] 배너 버튼
  - [ ] 인기 급상승 프로젝트 카드
  - [ ] Speed MatchUp 배너
  - [ ] 전체 프로젝트 카드 컴포넌트
  - [ ] 추천 프로젝트 카드 컴포넌트
  - [ ] 추천 프로젝트 캐러셀
- [x] 헤더 컴포넌트 CSS 변경사항 반영
- [x] 헤더 컴포넌트 경로이동 기능 추가
- [x] '/' 경로로 접근 시 '/main' 경로로 redirect 기능 추가

### 작업 기간

2024.01.03 ~ 2024.01.04

**Comment by seonnn** [comment]
2024.01.04 작업 중인 페이지의 디자인을 전반적으로 수정할 예정인 것으로 알림 받아 작업 hold
