### ISSUE TITLE
포트폴리오 상세 페이지

### ISSUE THREAD

**Issue by kangkyeongseo** [9weeks-app-web/team-3-sfacfolio#24]
### Todo

- [x] 포트폴리오 상세 페이지 레이아웃 구현
- [ ] 포트폴리오 상세 페이지 데이터 구현
- [x] 헤더 알림 드롭다운 
- [ ] 경로별 페이지 레이아웃

### 작업 기간

2024.01.09 ~ 2024.01.10
