### ISSUE TITLE
채용 상세 페이지

### ISSUE THREAD

**Issue by kangkyeongseo** [9weeks-app-web/team-3-sfacfolio#28]
### Todo

- [x]  채용 상세 페이지 레이아웃 구현 (/career/company/[id])
- [x]  채용 상세 페이지 데이터 연결
- [x] 구글 지도 API 연결

### 작업 기간

2023.01.05 ~ 2023.01.06
