### ISSUE TITLE
메인페이지 - 배너 캐러셀/실시간 인기 커뮤니티 섹션

### ISSUE THREAD

**Issue by kangkyeongseo** [9weeks-app-web/team-3-sfacfolio#3]
### Todo

- [x] 메인페이지 배너 캐러셀
- [x] 실시간 인기 커뮤니티 핫한 게시글 컴포넌트
- [x] 실시간 인기 커뮤니티 인기 키워드 컴포넌트

### 작업 기간

2023.12.29
