### ISSUE TITLE
메인 페이지 - 카드 컴포넌트 / 더보기 버튼 / 푸터 컴포넌트

### ISSUE THREAD

**Issue by geonwooPark** [9weeks-app-web/team-3-sfacfolio#4]
### Todo

- [x] 포트폴리오 카드 컴포넌트
- [x] 채용공고 카드 컴포넌트
- [x] 포트폴리오 & 채용공고 더보기 버튼
- [x] 푸터 컴포넌트

### 작업 기간

~ 2023.12.29
