### ISSUE TITLE
커뮤니티 메인 페이지

### ISSUE THREAD

**Issue by soprue** [9weeks-app-web/team-3-sfacfolio#45]
### Todo

- [x] 메인 배너 컴포넌트
- [x] 커뮤니티 메뉴 컴포넌트
- [x] 인기 키워드 컴포넌트
- [x] 검색 form 컴포넌트
- [x] 커뮤니티 글 목록
- [x] 커뮤니티 글 페이지네이션

### 작업 기간

2024.01.09
