### ISSUE TITLE
메인 페이지 - 헤더 컴포넌트/FIND 프로젝트 섹션 추가

### ISSUE THREAD

**Issue by seonnn** [9weeks-app-web/team-3-sfacfolio#5]
### Todo

- [x] 헤더 컴포넌트
  - [x] SearchBar 컴포넌트
  - [x] 로그인 & 회원가입 버튼
- [x] FIND 프로젝트 카드 컴포넌트
- [x] FIND 프로젝트 캐러셀
- [x] 프로젝트 매칭하기 배너

### 작업 기간

~ 2024.01.02(디자인 변경으로 인한 작업 기한 연장)

**Comment by seonnn** [comment]
231228 디자인 변경으로 인한 업무 재분장

**Comment by seonnn** [comment]
240102 디자인 변경으로 인한 작업 기한 연장(헤더컴포넌트 디자인이 240102 확정됨에 따라 작업 기한 231228 -> 240102로 변경)
