### ISSUE TITLE
마이페이지 최최종

### ISSUE THREAD

**Issue by soprue** [9weeks-app-web/team-3-sfacfolio#60]
### Todo

- [x] 마이페이지 포트폴리오 탭 레이아웃
- [x] 마이페이지 프로젝트 탭 레이아웃
- [x] 마이페이지 커뮤니티 탭 레이아웃
- [x] 마이페이지 스팩퀴즈 탭 레이아웃
- [x] 마이페이지 커리어 탭 레이아웃
- [x] 마이페이지 제안 관리 
- [ ] 마이페이지 팔로잉/팔로우

### 작업 기간

2024.01.09 - 2024.01.10
